repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v3.0.3' # Use the sha or tag you want to point at
      hooks:
          - id: prettier
    - repo: https://github.com/tekwizely/pre-commit-golang
      rev: v1.0.0-rc.1
      hooks:
          - id: go-fmt
          - id: go-fmt-repo
