repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: '' # Use the sha or tag you want to point at
      hooks:
          - id: prettier
    - repo: https://github.com/tekwizely/pre-commit-golang
      rev: master
      hooks:
          - id: go-fmt
          - id: go-fmt-repo
