version: '3.4'

services:
    db:
        env_file: .env.test

    server:
        image: golang:latest
        build:
            context: .
            dockerfile: docker/images/test/Dockerfile.server
        env_file: .env.test
        command: go test -v ./... -covermode=count -coverprofile=coverage.out

    app:
        command: bash -c "yarn test && yarn coverage"
