version: "3.4"

services:
    db:
        image: postgres:latest
        restart: always
        env_file: .env
        volumes:
            - postgresdata:/var/lib/postgresql/data

    server:
        build:
            context: .
            dockerfile: docker/images/dev/Dockerfile.server
        env_file: .env
        volumes:
            - .:/go/app/src:z
        ports:
            - 5000:8080
        command: go run server.go
        links:
            - db
        depends_on:
            - db

    app:
        build:
            context: .
            dockerfile: docker/images/dev/Dockerfile.app
        env_file: .env
        volumes:
            - .:/usr/src/app:z
        ports:
            - 3000:3000

    adminer:
        image: adminer:latest
        links:
            - db
        ports:
            - 8080:8080

volumes:
    postgresdata:
