version: "3.4"

services:
    db:
        image: postgres:13-alpine
        restart: always
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - postgresdata:/var/lib/postgresql/data

    server:
        image: cosmtrek/air
        env_file: .env
        volumes:
            - .:/go/app/src:z
        working_dir: /go/app/src
        ports:
            - "5000:5000"
        links:
            - db:database
        depends_on:
            - db

    web:
        build:
            context: .
            dockerfile: docker/images/dev/Dockerfile.apps
            target: web
        env_file: .env
        volumes:
            - .:/app:z
            - /app/apps/web/node_modules
            - /app/node_modules
        ports:
            - "3000:3000"

    mobile:
        build:
            context: .
            dockerfile: docker/images/dev/Dockerfile.apps
            target: mobile
        env_file: .env
        volumes:
            - .:/app:z
            - /app/node_modules
        ports:
            - "8082:8081"

    adminer:
        image: adminer:latest
        links:
            - db
        ports:
            - "8081:8080"

volumes:
    postgresdata:
