version: "3.4"

services:
    db:
        image: postgres:13-alpine
        restart: always
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - postgresdata:/var/lib/postgresql/data

    server:
        image: cosmtrek/air
        env_file: .env
        volumes:
            - .:/go/app/src:z
        working_dir: /go/app/src
        ports:
            - "5000:5000"
        links:
            - db:database
            - mailpit
        depends_on:
            - db

    web:
        build:
            context: .
            dockerfile: docker/images/dev/Dockerfile.apps
            target: web
        env_file: .env
        volumes:
            - .:/app:z
        ports:
            - "3000:3000"

    mobile:
        build:
            context: .
            dockerfile: docker/images/dev/Dockerfile.apps
            target: mobile
        env_file: .env
        volumes:
            - .:/app:z
        ports:
            - "19000:19000"
            - "19001:19001"
            - "19006:19006"
            - "8081:8081"
            - "8082:8082"
        environment:
            REACT_NATIVE_PACKAGER_HOSTNAME: "192.168.87.206"
            EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"

    adminer:
        image: adminer:latest
        links:
            - db
        ports:
            - "8083:8080"

    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"
        env_file: .env

volumes:
    postgresdata:
