version: '3.4'

services:
    db:
        image: postgres:13-alpine
        restart: always
        env_file: .env
        volumes:
            - postgresdata:/var/lib/postgresql/data

    server:
        image: cosmtrek/air
        env_file: .env
        volumes:
            - .:/go/app/src:z
        working_dir: /go/app/src
        ports:
            - 5000:5000
        links:
            - db:database
        depends_on:
            - db

    app:
        build:
            context: .
            dockerfile: docker/images/dev/Dockerfile.app
        env_file: .env
        volumes:
            - .:/usr/src/app:z
        ports:
            - 3000:3000

    adminer:
        image: adminer:latest
        links:
            - db
        ports:
            - 8081:8080

volumes:
    postgresdata:
