LABEL authors="da-max"

FROM node:20-slim as base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY .npmrc pnpm-lock.yaml pnpm-workspace.yaml ./
RUN mkdir -p apps/web apps/mobile
COPY apps/web/package.json ./apps/web/package.json
COPY apps/mobile/package.json ./apps/mobile/package.json

FROM base as install

RUN pnpm install

RUN ls /app/node_modules

FROM base as mobile
COPY --from=install /app/apps/mobile/node_modules /app/apps/mobile/node_modules
COPY --from=install /app/node_modules /app/node_modules

WORKDIR /app/apps/mobile

RUN ls /app/node_modules

EXPOSE 8081
CMD ["pnpm", "run", "start", "--port", "8081"]

FROM base as web
COPY --from=install /app/node_modules /app/node_modules

WORKDIR /app/apps/web

RUN ls /app/node_modules

EXPOSE 3000
CMD ["pnpm", "run", "dev"]
