LABEL authors="da-max"

FROM node:20-slim as init
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY .npmrc pnpm-workspace.yaml ./
RUN mkdir -p apps/web apps/mobile libs/colors
COPY apps/web/package.json apps/web/.npmrc ./apps/web/
COPY apps/mobile/package.json ./apps/mobile/package.json
COPY libs/colors/package.json ./libs/colors/package.json
COPY libs/core/package.json ./libs/core/package.json
COPY libs/eslint-config/package.json ./libs/eslint-config/package.json


FROM init as install

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

FROM init as base


FROM base as mobile

VOLUME ["/app/node_modules", "/app/libs/core/node_modules", "/app/apps/mobile/node_modules"]

COPY --from=install /app/apps/mobile/node_modules /app/apps/mobile/node_modules
COPY --from=install /app/node_modules /app/node_modules
COPY --from=install /app/libs/core/node_modules /app/libs/core/node_modules

WORKDIR /app

CMD ["pnpm", "run", "--parallel", "-r", "--filter", "!web", "start"]

FROM base as web

VOLUME ["/app/node_modules", "/app/libs/core/node_modules", "/app/apps/web/node_modules"]

COPY --from=install /app/node_modules /app/node_modules
COPY --from=install /app/apps/web/node_modules /app/apps/web/node_modules
COPY --from=install /app/libs/core/node_modules /app/libs/core/node_modules


WORKDIR /app

CMD ["pnpm", "run", "--parallel", "-r", "--filter", "!mobile", "start"]
