FROM golang:1.18-stretch as build

WORKDIR /usr/src/app

ENV GOARCH=amd64
ENV GOOS=linux

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build

FROM golang:1.18-stretch as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/todo-go ./todo-go

RUN chmod +x ./todo-go

CMD ["/usr/src/app/todo-go"]
