name: Build, push and deploy images for prod

on:
    push:
        branches:
            - main

jobs:
    build_push:
        runs-on: ubuntu-latest
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push app
              uses: docker/build-push-action@v3
              with:
                  push: true
                  file: docker/images/prod/Dockerfile.app
                  plateforms: linux/amd64
                  tags: |
                      ghcr.io/${{ github.repository }}-app:${{ github.ref_name }}
            - name: Build and push server
              uses: docker/build-push-action@v3
              with:
                  push: true
                  file: docker/images/prod/Dockerfile.server
                  plateforms: linux/amd64
                  tags: |
                      ghcr.io/${{ github.repository }}-server:${{ github.ref_name }}

    deploy:
        needs: build_push
        runs-on: ubuntu-latest
        steps:
            - name: Deploy image
              uses: appleboy/ssh-action@master
              env:
                  repository: ${{ github.repository }}
                  owner: ${{ github.repository_owner }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  password: ${{ secrets.DEPLOY_PASSWORD }}
                  envs: repository, owner, github_token
                  script: |
                      compose_file="$(echo "$repository" | sed -r "s/$owner\///g")"/docker-compose.yml
                      docker-compose login -u "$owner" -p "$github_token" ghcr.io
                      docker-compose -f "$compose_file" pull
                      docker-compose -f "$compose_file" stop && docker-compose -f "$compose_file" up -d
