name: Build, push and deploy images for prod

on:
    push:
        branches:
            - main

jobs:
    build_push:
        runs-on: ubuntu-latest
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push app
              uses: docker/build-push-action@v3
              with:
                  platforms: linux/amd64
                  push: true
                  file: docker/images/prod/Dockerfile.app
                  tags: |
                      ghcr.io/${{ github.repository }}-app:${{ github.ref_name }}
            - name: Build and push server
              uses: docker/build-push-action@v3
              with:
                  platforms: linux/amd64
                  push: true
                  file: docker/images/prod/Dockerfile.server
                  tags: |
                      ghcr.io/${{ github.repository }}-server:${{ github.ref_name }}

    deploy:
        needs: build_push
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Deploy image
              uses: appleboy/ssh-action@master
              env:
                  REPOSITORY: ${{ github.repository }}
                  OWNER: ${{ github.repository_owner }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  key: ${{ secrets.DEPLOY_PASSWORD }}
                  envs: REPOSITORY,OWNER,GITHUB_TOKEN,
                  script: |
                      compose_file=`echo $REPOSITORY | sed -r "s/$OWNER\///g"`/docker-compose.yml
                      docker login -u "$OWNER" -p "$GITHUB_TOKEN" ghcr.io
                      docker-compose -f "$compose_file" pull
                      docker-compose -f "$compose_file" stop && docker-compose -f "$compose_file" up -d
